# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/category_images/')),
                ('sort_order', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=1)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(100, 'active'), (101, 'inactive'), (102, 'coming soon'), (103, 'sold out')], db_index=True, default=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_available', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/product_images/')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('is_virtual', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_class', models.BooleanField(default=True)),
                ('ordered_count', models.IntegerField(default=0, editable=False)),
                ('quantity_order_min', models.FloatField(blank=True, null=True)),
                ('quantity_order_units', models.FloatField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('quantity_order_max', models.FloatField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('discount_type', models.IntegerField(choices=[(200, 'none'), (201, 'percentage discount'), (202, 'actual price'), (203, 'amount off discount')], default=200)),
                ('final_price', models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=10)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('viewed_count', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
