# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time_created',
        ),
        migrations.AddField(
            model_name='product',
            name='PRODUCT_DISCOUNT_TYPE',
            field=models.IntegerField(choices=[(200, 'none'), (201, 'percentage discount'), (202, 'actual price'), (203, 'amount off discount')], default=200),
        ),
        migrations.AddField(
            model_name='product',
            name='product_date_available',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_final_price',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='images/product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_ordered_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity_order_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity_order_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity_order_units',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.IntegerField(choices=[(100, 'active'), (101, 'inactive'), (102, 'coming soon'), (103, 'sold out')], db_index=True, default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tax_class',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_viewed_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
